# This is of test and example usage.
# This file has no errors.
Test:
  active: true
  server: localhost
  user: user
  port: 22
  file_1: ~/file.xml
  file_2: ~/file2.xml
  file_3: ~/file3.xml
  out_dir: ~/out/
 
